/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OutilsRouteImport } from './routes/outils'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as OutilsSlugRouteImport } from './routes/outils.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'

const OutilsRoute = OutilsRouteImport.update({
  id: '/outils',
  path: '/outils',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsSlugRoute = OutilsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OutilsRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/outils': typeof OutilsRouteWithChildren
  '/categories/$slug': typeof CategoriesSlugRoute
  '/outils/$slug': typeof OutilsSlugRoute
  '/categories/': typeof CategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/outils': typeof OutilsRouteWithChildren
  '/categories/$slug': typeof CategoriesSlugRoute
  '/outils/$slug': typeof OutilsSlugRoute
  '/categories': typeof CategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/outils': typeof OutilsRouteWithChildren
  '/categories/$slug': typeof CategoriesSlugRoute
  '/outils/$slug': typeof OutilsSlugRoute
  '/categories/': typeof CategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/outils'
    | '/categories/$slug'
    | '/outils/$slug'
    | '/categories/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/outils' | '/categories/$slug' | '/outils/$slug' | '/categories'
  id:
    | '__root__'
    | '/'
    | '/outils'
    | '/categories/$slug'
    | '/outils/$slug'
    | '/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OutilsRoute: typeof OutilsRouteWithChildren
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/outils': {
      id: '/outils'
      path: '/outils'
      fullPath: '/outils'
      preLoaderRoute: typeof OutilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils/$slug': {
      id: '/outils/$slug'
      path: '/$slug'
      fullPath: '/outils/$slug'
      preLoaderRoute: typeof OutilsSlugRouteImport
      parentRoute: typeof OutilsRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OutilsRouteChildren {
  OutilsSlugRoute: typeof OutilsSlugRoute
}

const OutilsRouteChildren: OutilsRouteChildren = {
  OutilsSlugRoute: OutilsSlugRoute,
}

const OutilsRouteWithChildren =
  OutilsRoute._addFileChildren(OutilsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OutilsRoute: OutilsRouteWithChildren,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
